import _ from 'lodash';

const TRAIT_ID_AND_NAME: [string, string][] = [
  // Emotional Disposition
  ['optimistic', 'Optimistic'],
  ['pessimistic', 'Pessimistic'],
  ['nostalgic', 'Nostalgic'],
  ['depressed', 'Depressed'],
  ['gloomy', 'Gloomy'],
  ['guilt_ridden', 'Guilt-Ridden'],
  ['emotionally_scarred', 'Emotionally Scarred'],
  ['anxious', 'Anxious'],
  ['nervous', 'Nervous'],
  ['bored', 'Bored'],
  ['content', 'Content'],
  ['resilient', 'Resilient'],

  // Social Orientation
  ['outgoing', 'Outgoing'],
  ['shy', 'Shy'],
  ['extroverted', 'Extroverted'],
  ['introverted', 'Introverted'],
  ['social', 'Social'],
  ['lonely', 'Lonely'],
  ['reserved', 'Reserved'],
  ['flirtatious', 'Flirtatious'],
  ['charming', 'Charming'],
  ['charismatic', 'Charismatic'],
  ['awkward', 'Awkward'],
  ['mistrusting', 'Mistrusting'],
  ['guarded', 'Guarded'],
  ['friendly', 'Friendly'],
  ['private', 'Private'],
  ['gossipy', 'Gossipy'],

  // Interpersonal Behavior
  ['caring', 'Caring'],
  ['cold', 'Cold'],
  ['empathetic', 'Empathetic'],
  ['selfless', 'Selfless'],
  ['generous', 'Generous'],
  ['stingy', 'Stingy'],
  ['supportive', 'Supportive'],
  ['judgmental', 'Judgmental'],
  ['protective', 'Protective'],
  ['clingy', 'Clingy'],
  ['independent', 'Independent'],
  ['affectionate', 'Affectionate'],
  ['diplomatic', 'Diplomatic'],
  ['argumentative', 'Argumentative'],
  ['attentive', 'Attentive'],
  ['detached', 'Detached'],
  ['gentle', 'Gentle'],
  ['aggressive', 'Aggressive'],
  ['dominant', 'Dominant'],
  ['submissive', 'Submissive'],

  // Moral / Ethical
  ['honest', 'Honest'],
  ['deceptive', 'Deceptive'],
  ['manipulative', 'Manipulative'],
  ['loyal', 'Loyal'],
  ['fickle', 'Fickle'],
  ['vengeful', 'Vengeful'],
  ['vindictive', 'Vindictive'],
  ['merciful', 'Merciful'],
  ['ruthless', 'Ruthless'],
  ['bigoted', 'Bigoted'],
  ['hypocritical', 'Hypocritical'],
  ['crafty', 'Crafty'],
  ['secretive', 'Secretive'],
  ['shameless', 'Shameless'],

  // Self-Perception
  ['confident', 'Confident'],
  ['insecure', 'Insecure'],
  ['proud', 'Proud'],
  ['humble', 'Humble'],
  ['arrogant', 'Arrogant'],
  ['narcissistic', 'Narcissistic'],
  ['self_aware', 'Self-Aware'],
  ['introspective', 'Introspective'],
  ['self_reflective', 'Self-Reflective'],
  ['haughty', 'Haughty'],
  ['smug', 'Smug'],

  // Drive & Motivation
  ['ambitious', 'Ambitious'],
  ['driven', 'Driven'],
  ['workaholic', 'Workaholic'],
  ['lazy', 'Lazy'],
  ['determined', 'Determined'],
  ['apathetic', 'Apathetic'],
  ['idealistic', 'Idealistic'],
  ['realistic', 'Realistic'],
  ['passionate', 'Passionate'],
  ['competitive', 'Competitive'],
  ['cooperative', 'Cooperative'],

  // Cognitive Style
  ['analytical', 'Analytical'],
  ['creative', 'Creative'],
  ['curious', 'Curious'],
  ['studious', 'Studious'],
  ['intelligent', 'Intelligent'],
  ['scatterbrained', 'Scatterbrained'],
  ['calculating', 'Calculating'],
  ['pragmatic', 'Pragmatic'],
  ['dreamy', 'Dreamy'],
  ['delusional', 'Delusional'],
  ['skeptical', 'Skeptical'],
  ['naive', 'Naive'],
  ['observant', 'Observant'],
  ['witty', 'Witty'],

  // Behavioral Tendencies
  ['impulsive', 'Impulsive'],
  ['patient', 'Patient'],
  ['impatient', 'Impatient'],
  ['organized', 'Organized'],
  ['chaotic', 'Chaotic'],
  ['meticulous', 'Meticulous'],
  ['disciplined', 'Disciplined'],
  ['rebellious', 'Rebellious'],
  ['cautious', 'Cautious'],
  ['reckless', 'Reckless'],
  ['spontaneous', 'Spontaneous'],
  ['adventurous', 'Adventurous'],
  ['homebody', 'Homebody'],
  ['risk_taker', 'Risk Taker'],
  ['risk_averse', 'Risk Averse'],
  ['perfectionist', 'Perfectionist'],
  ['easygoing', 'Easygoing'],
  ['decisive', 'Decisive'],
  ['indecisive', 'Indecisive'],
  ['punctual', 'Punctual'],
  ['resourceful', 'Resourceful'],
  ['frugal', 'Frugal'],
  ['neat', 'Neat'],
  ['messy', 'Messy'],
  ['adrenaline_seeker', 'Adrenaline Seeker'],

  // Expression & Energy
  ['energetic', 'Energetic'],
  ['high_energy', 'High Energy'],
  ['low_energy', 'Low Energy'],
  ['expressive', 'Expressive'],
  ['stoic', 'Stoic'],
  ['dramatic', 'Dramatic'],
  ['calm', 'Calm'],
  ['playful', 'Playful'],
  ['serious', 'Serious'],
  ['humorous', 'Humorous'],
  ['sarcastic', 'Sarcastic'],
  ['snarky', 'Snarky'],
  ['earnest', 'Earnest'],
  ['outspoken', 'Outspoken'],
  ['attention_seeking', 'Attention Seeking'],
  ['captivating', 'Captivating'],
  ['sensitive', 'Sensitive'],

  // Social Roles & Leadership
  ['leader', 'Leader'],
  ['follower', 'Follower'],
  ['mentor_type', 'Mentor Type'],
  ['assertive', 'Assertive'],
  ['timid', 'Timid'],

  // Values & Worldview
  ['conservative', 'Conservative'],
  ['open_minded', 'Open-Minded'],
  ['traditional', 'Traditional'],
  ['spiritual', 'Spiritual'],
  ['nihilistic', 'Nihilistic'],
  ['practical', 'Practical'],
  ['blunt', 'Blunt'],
  ['polite', 'Polite'],

  // Complex / Archetypal
  ['obsessive', 'Obsessive'],
  ['jealous', 'Jealous'],
  ['envious', 'Envious'],
  ['possessive', 'Possessive'],
  ['spoiled', 'Spoiled'],
  ['defiant', 'Defiant'],
  ['unpredictable', 'Unpredictable'],
  ['romantic', 'Romantic'],
  ['artistic', 'Artistic'],
  ['grounded', 'Grounded'],
  ['stubborn', 'Stubborn'],
  ['clumsy', 'Clumsy'],
  ['skilled', 'Skilled'],
  ['mercurial', 'Mercurial'],
  ['demanding', 'Demanding'],
  ['duty_oriented', 'Duty-Oriented'],
  ['dutiful', 'Dutiful'],
  ['fierce', 'Fierce'],
  ['confrontational', 'Confrontational'],
  ['tsundere', 'Tsundere'],
  ['sadistic', 'Sadistic'],
  ['sophisticated', 'Sophisticated'],
];

const BAN_PAIRS: [string, string][] = [
  // ── Emotional ──
  ['optimistic', 'pessimistic'],
  ['optimistic', 'gloomy'],
  ['optimistic', 'nihilistic'],
  ['optimistic', 'depressed'],
  ['optimistic', 'emotionally_scarred'],
  ['pessimistic', 'idealistic'],
  ['depressed', 'high_energy'],
  ['gloomy', 'high_energy'],
  ['high_energy', 'low_energy'],
  ['content', 'workaholic'],
  ['content', 'ambitious'],
  ['bored', 'curious'],
  ['bored', 'passionate'],
  ['anxious', 'calm'],
  ['anxious', 'confident'],
  ['nervous', 'calm'],
  ['nervous', 'confident'],
  ['resilient', 'depressed'],
  ['guilt_ridden', 'shameless'],
  ['guilt_ridden', 'narcissistic'],

  // ── Social Orientation ──
  ['outgoing', 'shy'],
  ['outgoing', 'guarded'],
  ['outgoing', 'lonely'],
  ['outgoing', 'private'],
  ['extroverted', 'introverted'],
  ['extroverted', 'lonely'],
  ['extroverted', 'guarded'],
  ['shy', 'flirtatious'],
  ['shy', 'assertive'],
  ['shy', 'outspoken'],
  ['reserved', 'flirtatious'],
  ['reserved', 'outspoken'],
  ['reserved', 'expressive'],
  ['social', 'lonely'],
  ['friendly', 'guarded'],
  ['friendly', 'cold'],
  ['mistrusting', 'friendly'],
  ['mistrusting', 'social'],
  ['mistrusting', 'supportive'],
  ['guarded', 'flirtatious'],
  ['guarded', 'social'],
  ['charming', 'awkward'],
  ['captivating', 'awkward'],
  ['gossipy', 'private'],

  // ── Interpersonal Behavior ──
  ['caring', 'cold'],
  ['caring', 'detached'],
  ['caring', 'ruthless'],
  ['cold', 'empathetic'],
  ['cold', 'affectionate'],
  ['cold', 'sensitive'],
  ['empathetic', 'detached'],
  ['empathetic', 'sadistic'],
  ['empathetic', 'narcissistic'],
  ['empathetic', 'manipulative'],
  ['selfless', 'narcissistic'],
  ['selfless', 'stingy'],
  ['selfless', 'jealous'],
  ['selfless', 'vengeful'],
  ['selfless', 'ruthless'],
  ['selfless', 'manipulative'],
  ['selfless', 'vindictive'],
  ['generous', 'stingy'],
  ['supportive', 'judgmental'],
  ['supportive', 'detached'],
  ['supportive', 'jealous'],
  ['affectionate', 'detached'],
  ['affectionate', 'cold'],
  ['clingy', 'detached'],
  ['protective', 'ruthless'],
  ['gentle', 'aggressive'],
  ['gentle', 'ruthless'],
  ['gentle', 'sadistic'],
  ['gentle', 'fierce'],
  ['dominant', 'submissive'],
  ['dominant', 'follower'],
  ['assertive', 'timid'],
  ['assertive', 'submissive'],
  ['assertive', 'indecisive'],
  ['timid', 'outspoken'],
  ['timid', 'dominant'],
  ['submissive', 'leader'],
  ['diplomatic', 'argumentative'],
  ['diplomatic', 'confrontational'],
  ['aggressive', 'calm'],
  ['aggressive', 'patient'],
  ['aggressive', 'diplomatic'],
  ['confrontational', 'calm'],
  ['confrontational', 'diplomatic'],
  ['detached', 'passionate'],
  ['detached', 'romantic'],
  ['attentive', 'apathetic'],
  ['attentive', 'scatterbrained'],

  // ── Moral / Ethical ──
  ['honest', 'deceptive'],
  ['honest', 'manipulative'],
  ['honest', 'crafty'],
  ['loyal', 'fickle'],
  ['ruthless', 'merciful'],
  ['vengeful', 'merciful'],
  ['vengeful', 'calm'],
  ['vindictive', 'merciful'],
  ['sadistic', 'merciful'],
  ['sadistic', 'caring'],
  ['sadistic', 'gentle'],
  ['shameless', 'humble'],
  ['shameless', 'insecure'],
  ['bigoted', 'open_minded'],
  ['bigoted', 'empathetic'],
  ['bigoted', 'diplomatic'],
  ['crafty', 'earnest'],
  ['manipulative', 'selfless'],
  ['hypocritical', 'earnest'],
  ['hypocritical', 'self_aware'],

  // ── Self-Perception ──
  ['confident', 'insecure'],
  ['proud', 'humble'],
  ['proud', 'selfless'],
  ['arrogant', 'humble'],
  ['arrogant', 'insecure'],
  ['narcissistic', 'humble'],
  ['narcissistic', 'selfless'],
  ['narcissistic', 'self_aware'],
  ['haughty', 'humble'],
  ['haughty', 'selfless'],
  ['smug', 'humble'],
  ['smug', 'insecure'],

  // ── Drive & Motivation ──
  ['driven', 'apathetic'],
  ['driven', 'lazy'],
  ['driven', 'scatterbrained'],
  ['ambitious', 'content'],
  ['workaholic', 'easygoing'],
  ['workaholic', 'content'],
  ['lazy', 'studious'],
  ['lazy', 'workaholic'],
  ['lazy', 'driven'],
  ['lazy', 'duty_oriented'],
  ['lazy', 'dutiful'],
  ['passionate', 'apathetic'],
  ['passionate', 'stoic'],
  ['idealistic', 'nihilistic'],
  ['idealistic', 'realistic'],
  ['idealistic', 'calculating'],
  ['realistic', 'delusional'],
  ['competitive', 'cooperative'],
  ['determined', 'apathetic'],
  ['determined', 'indecisive'],

  // ── Cognitive Style ──
  ['analytical', 'dreamy'],
  ['analytical', 'delusional'],
  ['pragmatic', 'romantic'],
  ['pragmatic', 'dreamy'],
  ['pragmatic', 'artistic'],
  ['delusional', 'skeptical'],
  ['delusional', 'grounded'],
  ['delusional', 'intelligent'],
  ['skeptical', 'naive'],
  ['skeptical', 'spiritual'],
  ['grounded', 'dreamy'],
  ['naive', 'calculating'],
  ['naive', 'manipulative'],
  ['scatterbrained', 'organized'],
  ['scatterbrained', 'meticulous'],
  ['scatterbrained', 'driven'],
  ['intelligent', 'scatterbrained'],
  ['observant', 'apathetic'],
  ['observant', 'scatterbrained'],

  // ── Behavioral Tendencies ──
  ['patient', 'impulsive'],
  ['impatient', 'patient'],
  ['impatient', 'calm'],
  ['organized', 'chaotic'],
  ['organized', 'messy'],
  ['organized', 'unpredictable'],
  ['neat', 'messy'],
  ['meticulous', 'unpredictable'],
  ['meticulous', 'scatterbrained'],
  ['disciplined', 'rebellious'],
  ['disciplined', 'defiant'],
  ['cautious', 'reckless'],
  ['cautious', 'risk_taker'],
  ['risk_taker', 'risk_averse'],
  ['adventurous', 'homebody'],
  ['adventurous', 'risk_averse'],
  ['homebody', 'adrenaline_seeker'],
  ['spontaneous', 'frugal'],
  ['spontaneous', 'meticulous'],
  ['perfectionist', 'easygoing'],
  ['perfectionist', 'scatterbrained'],
  ['decisive', 'indecisive'],
  ['decisive', 'unpredictable'],
  ['mercurial', 'organized'],
  ['mercurial', 'meticulous'],
  ['mercurial', 'grounded'],
  ['mercurial', 'decisive'],
  ['sophisticated', 'messy'],
  ['sophisticated', 'chaotic'],

  // ── Expression & Energy ──
  ['energetic', 'low_energy'],
  ['energetic', 'depressed'],
  ['stoic', 'dramatic'],
  ['stoic', 'sensitive'],
  ['stoic', 'expressive'],
  ['stoic', 'passionate'],
  ['calm', 'dramatic'],
  ['calm', 'aggressive'],
  ['playful', 'serious'],
  ['humorous', 'serious'],
  ['sarcastic', 'earnest'],
  ['snarky', 'earnest'],
  ['snarky', 'polite'],
  ['snarky', 'kind'],
  ['expressive', 'detached'],
  ['outspoken', 'reserved'],
  ['introspective', 'extroverted'],
  ['introspective', 'outspoken'],

  // ── Social Roles ──
  ['leader', 'follower'],
  ['leader', 'submissive'],

  // ── Values & Worldview ──
  ['conservative', 'open_minded'],
  ['conservative', 'rebellious'],
  ['conservative', 'risk_taker'],
  ['traditional', 'open_minded'],
  ['traditional', 'rebellious'],
  ['traditional', 'defiant'],
  ['open_minded', 'stubborn'],
  ['nihilistic', 'idealistic'],
  ['nihilistic', 'optimistic'],
  ['spiritual', 'skeptical'],
  ['duty_oriented', 'rebellious'],
  ['duty_oriented', 'chaotic'],
  ['duty_oriented', 'defiant'],
  ['dutiful', 'rebellious'],
  ['dutiful', 'chaotic'],
  ['dutiful', 'defiant'],

  // ── Complex / Archetypal ──
  ['obsessive', 'easygoing'],
  ['obsessive', 'calm'],
  ['obsessive', 'apathetic'],
  ['spoiled', 'humble'],
  ['spoiled', 'disciplined'],
  ['spoiled', 'selfless'],
  ['spoiled', 'frugal'],
  ['defiant', 'disciplined'],
  ['defiant', 'dutiful'],
  ['defiant', 'duty_oriented'],
  ['jealous', 'selfless'],
  ['jealous', 'supportive'],
  ['envious', 'content'],
  ['envious', 'selfless'],
  ['unpredictable', 'organized'],
  ['unpredictable', 'meticulous'],
  ['unpredictable', 'decisive'],
  ['romantic', 'detached'],
  ['tsundere', 'detached'],
  ['stubborn', 'open_minded'],
  ['skilled', 'clumsy'],
  ['demanding', 'easygoing'],
  ['demanding', 'patient'],
  ['fierce', 'gentle'],
  ['fierce', 'calm'],
  ['fierce', 'merciful'],
];

function buildBanMap(pairs: [string, string][]): Record<string, string[]> {
  const map: Record<string, string[]> = {};
  for (const [a, b] of pairs) {
    if (!map[a]) map[a] = [];
    if (!map[b]) map[b] = [];
    if (!map[a].includes(b)) map[a].push(b);
    if (!map[b].includes(a)) map[b].push(a);
  }
  return map;
}

const BAN_MAP = buildBanMap(BAN_PAIRS);

const characterTraits = TRAIT_ID_AND_NAME.map(([traitId, traitName]) => ({
  traitId,
  traitName,
  bannedSiblings: BAN_MAP[traitId as string] || [],
}));

export function generatePersonalityTraits(): string[] {
  const selected: string[] = [];
  const banned = new Set<string>();
  const shuffled = _.shuffle(characterTraits);

  for (const trait of shuffled) {
    const traitName = trait.traitName;
    if (selected.length >= 4) {
      break;
    }

    if (banned.has(traitName)) {
      continue;
    }

    selected.push(traitName);
    for (const sibling of trait.bannedSiblings) {
      banned.add(sibling);
    }
  }

  return selected;
}
